# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0


name: Build, Test and Release

on:
  # run pipeline from another workflow
  workflow_call:
    inputs:
      create_release:
        type: boolean
        description: Create a (pre-)release when CI passes
        default: false
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-main
  cancel-in-progress: true

jobs:

  build-python:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set PyPI version
        uses: PowerGridModel/pgm-version-bump@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          cat PYPI_VERSION
          pip install build
          python -m build --outdir wheelhouse .

      - name: Save version
        id: version
        run: echo "version=$(cat PYPI_VERSION)" >> $GITHUB_OUTPUT

      - name: Store built wheel file
        uses: actions/upload-artifact@v4
        with:
          name: power-grid-model-ds
          path: wheelhouse/

  tests:
    needs: build-python
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.11", "3.12", "3.13"]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Load built wheel file
        uses: actions/download-artifact@v4
        with:
          name: power-grid-model-ds
          path: wheelhouse/

      - name: Install built wheel file
        run: pip install power-grid-model-ds[dev]==${{ needs.build-python.outputs.version }} --find-links=wheelhouse

      - name: Unit test and coverage
        run: pytest --verbose

  github-release:
    needs:
      - build-python
      - tests
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Checkout source code
        uses: actions/checkout@v4  # needed by 'Prevent automatic major/minor release'

      - name: Load built wheel file
        uses: actions/download-artifact@v4
        with:
          name: power-grid-model-ds
          path: wheelhouse/

      - name: Prevent automatic major/minor release
        if: (github.event_name == 'push')
        run: |
          echo "Fetching the latest release..."
          tag=$(gh release view --json tagName --jq '.tagName')
          tag=${tag#v}  # Remove the leading 'v'
          major_minor=$(echo "$tag" | cut -d. -f1,2)
          version_file=$(cat VERSION)

          if [ "$major_minor" = "$version_file" ]; then
            echo "Patch release detected. Proceeding with automatic release."
          else
            echo "Cannot automatically release a new major/minor version. Please trigger manually if desired."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag
        id: tag
        run: echo "tag=v${{ needs.build-python.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Display tag
        run: echo "${{ steps.tag.outputs.tag }}"

      - name: Release
        if: (inputs.create_release)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./wheelhouse/*
          tag_name: ${{ steps.tag.outputs.tag }}
          prerelease: ${{github.ref != 'refs/heads/main'}}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
