# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0

name: Sonar Cloud

on:
  # run pipeline on push event of main branch
  push:
    branches:
      - main
  # run pipeline on pull request
  pull_request:
  # run pipeline on merge queue
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-sonar
  cancel-in-progress: true

jobs:
  sonar-cloud:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        if: ${{ always() }}
        with:
          activate-environment: true
          enable-cache: true

      - name: install poe
        run: uv tool install poethepoet

      - name: Install dependencies
        if: ${{ always() }}
        run: uv sync --dev

      - name: Test and Coverage
        run: |
          poe coverage
          uv run coverage xml 

      - name: SonarCloud Scan
        if: ${{ (github.event_name == 'push') || (github.event.pull_request.head.repo.owner.login == 'PowerGridModel') }}
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
